# logging="DEBUG"
nat-method="AUTO"
host-allowlist=["*"]
min-gas-price=0
miner-enabled=true
miner-coinbase="fe3b557e8fb62b89f4916b721be55ceb828dbd73"

p2p-port=30303

# RPC HTTP related
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-api=["ADMIN", "IBFT", "QBFT", "CLIQUE", "ETH", "NET", "TXPOOL", "WEB3"]
rpc-http-cors-origins=["all"]

# RPC WS related
rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546

# metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9091

tx-pool-limit-by-account-percentage=1
