version: "3.4"

networks:
  besu-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24

services:
  node-1:
    container_name: node-1
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu --data-path=/opt/besu/data \
        --genesis-file=/opt/besu/genesis.json --rpc-http-enabled --rpc-http-port=8545 \
        --host-allowlist="*" --rpc-http-cors-origins="all" \
        --rpc-http-api=ADMIN, IBFT, QBFT, CLIQUE, ETH, NET, TXPOOL, WEB3 \
        --rpc-ws-enabled --rpc-ws-port=8546 --p2p-port=30303 --min-gas-price=0 \
        --miner-coinbase f17f52151EbEF6C7334FAD080c5704D77216b732 \
        --logging=DEBUG;
    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./nodes/node-1/data:/opt/besu/data
    networks:
      besu-network:
        ipv4_address: 172.16.239.8
