version: '3.4'

networks:
  besu-sc_besu-network:
    external: true
  
services:  
  api:
    image: web3labs/epirus-free-api:latest
    environment:
      - NODE_ENDPOINT=http://172.16.239.18:8545
      - MONGO_CLIENT_URI=mongodb://mongodb:27017
      - REINDEX_ENDPOINT=http://ingestion/reindex/
      - MONGO_DB_NAME=epirus
      - MONGO_CREATE_INDICES=true
    depends_on:
      - mongodb
    networks:
      besu-sc_besu-network:
        ipv4_address: 172.16.239.19
  mongodb:
    image: mongo:5.0.8
    environment:
      - COMPOSE_HTTP_TIMEOUT=900
      - DOCKER_CLIENT_TIMEOUT=900
    entrypoint: mongod --bind_ip "0.0.0.0"
    networks:
      besu-sc_besu-network:
        ipv4_address: 172.16.239.20
  web:
    image: web3labs/epirus-free-web:latest
    environment:
      - API_URL=/api
      - DISPLAY_NETWORK_TAB=disabled
    depends_on:
      - api
    networks:
      besu-sc_besu-network:
        ipv4_address: 172.16.239.21
  ingestion:
    image: web3labs/epirus-free-ingestion:latest
    environment:
      - NODE_ENDPOINT=http://172.16.239.8:8545
      - MONGO_CLIENT_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=epirus
    depends_on:
      - mongodb
    networks:
      besu-sc_besu-network:
        ipv4_address: 172.16.239.22
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./5xx.html:/www/error_pages/5xx.html
    depends_on:
      - mongodb
    networks:
      besu-sc_besu-network:
        ipv4_address: 172.16.239.23